version: '3'

networks:
  flask_app_network:
    name: flask_app_network

services:

  mysql:
    image: mysql:latest
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: Barca2381843
      MYSQL_DATABASE: task
    ports:
      - "3307:3306"
    networks:
      - flask_app_network
  
  webserver:
    build: .
    environment:
      DATABASE_CONNECT: mysql://root:Barca2381843@db:3306/task
    depends_on:
      - mysql
    ports:
       - "5000:5000"
    networks:
      - flask_app_network
    expose:
      - 5000
  
  webserver.test:
    build: .
    environment:
      DATABASE_CONNECT: mysql://root:Barca2381843@db:3306/task
    depends_on:
      - mysql
    networks:
      - flask_app_network
    entrypoint: python3 -m pytest