"""add models

Revision ID: 6fe2645bc70e
Revises: 6f6d8938609c
Create Date: 2022-04-28 13:42:40.998457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe2645bc70e'
down_revision = '6f6d8938609c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
